// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMemberAPI.Models;

public partial class TApply
{
    public int FId { get; set; }

    public int FUserId { get; set; }

    public string FStoreName { get; set; }

    public string FStoreDescription { get; set; }

    public string FIdNum { get; set; }

    public string FIdCard { get; set; }

    public int FStatus { get; set; }

    public DateTime FSendingDate { get; set; }

    public virtual TApplyStatus FStatusNavigation { get; set; }

    public virtual TUser FUser { get; set; }
}