// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMemberAPI.Models;

public partial class TApplyStatus
{
    public int FId { get; set; }

    public string FApplyStatusName { get; set; }

    public virtual ICollection<TApply> TApplies { get; set; } = new List<TApply>();
}