// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMemberAPI.Models;

public partial class TEmailVerification
{
    public int FId { get; set; }

    public int FUserId { get; set; }

    public string FToken { get; set; }

    public string FType { get; set; }

    public DateTime FExpireAt { get; set; }

    public DateTime? FUsedAt { get; set; }

    public DateTime? FCreatedAt { get; set; }

    public virtual TUser FUser { get; set; }
}