// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace prjMemberAPI.Models;

public partial class tempdbContext : DbContext
{
    public tempdbContext(DbContextOptions<tempdbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TApply> TApplies { get; set; }

    public virtual DbSet<TApplyStatus> TApplyStatuses { get; set; }

    public virtual DbSet<TSeller> TSellers { get; set; }

    public virtual DbSet<TStatus> TStatuses { get; set; }

    public virtual DbSet<TUser> TUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TApply>(entity =>
        {
            entity.HasKey(e => e.FId).HasName("PK__tApply__D9F8227CCE7B352D");

            entity.ToTable("tApply");

            entity.Property(e => e.FId)
                .ValueGeneratedNever()
                .HasColumnName("fId");
            entity.Property(e => e.FIdCard)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("fIdCard");
            entity.Property(e => e.FIdNum)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fIdNum");
            entity.Property(e => e.FSendingDate)
                .HasColumnType("datetime")
                .HasColumnName("fSendingDate");
            entity.Property(e => e.FStatus).HasColumnName("fStatus");
            entity.Property(e => e.FStoreDescription)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("fStoreDescription");
            entity.Property(e => e.FStoreName)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("fStoreName");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");

            entity.HasOne(d => d.FStatusNavigation).WithMany(p => p.TApplies)
                .HasForeignKey(d => d.FStatus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Apply_Status");

            entity.HasOne(d => d.FUser).WithMany(p => p.TApplies)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Apply_User");
        });

        modelBuilder.Entity<TApplyStatus>(entity =>
        {
            entity.HasKey(e => e.FId).HasName("PK__tApplySt__D9F8227CF3D77F25");

            entity.ToTable("tApplyStatus");

            entity.Property(e => e.FId)
                .ValueGeneratedNever()
                .HasColumnName("fId");
            entity.Property(e => e.FApplyStatusName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fApplyStatusName");
        });

        modelBuilder.Entity<TSeller>(entity =>
        {
            entity.HasKey(e => e.FId).HasName("PK__tSeller__D9F8227CA7A00A8B");

            entity.ToTable("tSeller");

            entity.Property(e => e.FId).HasColumnName("fId");
            entity.Property(e => e.FApplyDate)
                .HasColumnType("datetime")
                .HasColumnName("fApplyDate");
            entity.Property(e => e.FDescription)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("fDescription");
            entity.Property(e => e.FSellerName)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("fSellerName");
            entity.Property(e => e.FStatus).HasColumnName("fStatus");
            entity.Property(e => e.FUserId).HasColumnName("fUserId");

            entity.HasOne(d => d.FStatusNavigation).WithMany(p => p.TSellers)
                .HasForeignKey(d => d.FStatus)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Seller_Status");

            entity.HasOne(d => d.FUser).WithMany(p => p.TSellers)
                .HasForeignKey(d => d.FUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Seller_User");
        });

        modelBuilder.Entity<TStatus>(entity =>
        {
            entity.HasKey(e => e.FId).HasName("PK__tStatus__D9F8227C4D4C6E42");

            entity.ToTable("tStatus");

            entity.Property(e => e.FId)
                .ValueGeneratedNever()
                .HasColumnName("fId");
            entity.Property(e => e.FStatusName)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fStatusName");
        });

        modelBuilder.Entity<TUser>(entity =>
        {
            entity.HasKey(e => e.FId).HasName("PK__tUser__D9F8227C808E6864");

            entity.ToTable("tUser");

            entity.HasIndex(e => e.FUsername, "UQ__tUser__A8F6564AE2A92FB7").IsUnique();

            entity.Property(e => e.FId).HasColumnName("fId");
            entity.Property(e => e.FAddress)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("fAddress");
            entity.Property(e => e.FCreateTime)
                .HasColumnType("datetime")
                .HasColumnName("fCreateTime");
            entity.Property(e => e.FEmail)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("fEmail");
            entity.Property(e => e.FIdNum)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fIdNum");
            entity.Property(e => e.FImage)
                .IsUnicode(false)
                .HasColumnName("fImage");
            entity.Property(e => e.FIsActive).HasColumnName("fIsActive");
            entity.Property(e => e.FIsAdmin).HasColumnName("fIsAdmin");
            entity.Property(e => e.FLastLogin)
                .HasColumnType("datetime")
                .HasColumnName("fLastLogin");
            entity.Property(e => e.FPassword)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("fPassword");
            entity.Property(e => e.FPhone)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("fPhone");
            entity.Property(e => e.FUsername)
                .IsRequired()
                .HasMaxLength(16)
                .IsUnicode(false)
                .HasColumnName("fUsername");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}