// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMemberAPI.Models;

public partial class TSeller
{
    public int FId { get; set; }

    public int FUserId { get; set; }

    public string FSellerName { get; set; }

    public string FDescription { get; set; }

    public int FStatus { get; set; }

    public DateTime FApplyDate { get; set; }

    public virtual TStatus FStatusNavigation { get; set; }

    public virtual TUser FUser { get; set; }
}