// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMemberAPI.Models;

public partial class TStatus
{
    public int FId { get; set; }

    public string FStatusName { get; set; }

    public virtual ICollection<TSeller> TSellers { get; set; } = new List<TSeller>();
}