// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prjMemberAPI.Models;

public partial class TUser
{
    public int FId { get; set; }

    

    public string FUsername { get; set; }

    public string FPassword { get; set; }

    public string FEmail { get; set; }

    public string FPhone { get; set; }

    public string FIdNum { get; set; }

    public string FAddress { get; set; }

    public string FImage { get; set; }

    public bool FIsActive { get; set; }

    public bool FIsAdmin { get; set; }

    public DateTime FCreateTime { get; set; }

    public DateTime? FLastLogin { get; set; }

    public virtual ICollection<TApply> TApplies { get; set; } = new List<TApply>();

    public virtual ICollection<TSeller> TSellers { get; set; } = new List<TSeller>();
}